steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'newUser'
  args: ['functions',
  'deploy',
  'newUser',
  '--source=./new-user/.',
  '--trigger-event=providers/cloud.firestore/eventTypes/document.create',
  '--trigger-resource=projects/readcycle/databases/default/documents/userLocations/{user}',
  '--runtime=nodejs8']
