steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - newUser
  - --source=./new-user/.
  - --trigger-event=providers/cloud.firestore/eventTypes/document.create
  - --trigger-resource=userLocations/{user}
  - --runtime=nodejs8
